-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2021-01-06 20:09:43 IST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE admin (
    id         INTEGER NOT NULL,
    user_name  VARCHAR2(40),
    password   VARCHAR2(60)
);

ALTER TABLE admin ADD CONSTRAINT admin_pk PRIMARY KEY ( id );

CREATE TABLE bank_account (
    account_no       INTEGER NOT NULL,
    bank_name        VARCHAR2(40),
    balance          INTEGER,
    user_details_id  INTEGER NOT NULL
);

ALTER TABLE bank_account ADD CONSTRAINT bank_account_pk PRIMARY KEY ( account_no );

CREATE TABLE booking (
    pnr               INTEGER NOT NULL,
    date_of_booking   DATE,
    passengers        NUMBER(3),
    pnr_return        INTEGER,
    price             NUMBER(10, 2),
    user_details_id   INTEGER NOT NULL,
    flight_flight_no  INTEGER NOT NULL
);

ALTER TABLE booking ADD CONSTRAINT booking_pk PRIMARY KEY ( pnr );

CREATE TABLE flight (
    flight_no    INTEGER NOT NULL,
    flight_name  VARCHAR2(40)
);

ALTER TABLE flight ADD CONSTRAINT flight_pk PRIMARY KEY ( flight_no );

CREATE TABLE log (
    id           INTEGER NOT NULL,
    status       VARCHAR2(10),
    logtime      DATE,
    booking_pnr  INTEGER NOT NULL
);

ALTER TABLE log ADD CONSTRAINT log_pk PRIMARY KEY ( id );

CREATE TABLE passenger (
    id                 INTEGER NOT NULL,
    first_name         VARCHAR2(40),
    last_name          VARCHAR2(40),
    age                NUMBER(3),
    class_type         VARCHAR2(10),
    seat_no            NUMBER(3),
    type_of_passenger  VARCHAR2(10),
    booking_pnr        INTEGER NOT NULL
);

ALTER TABLE passenger ADD CONSTRAINT passenger_pk PRIMARY KEY ( id );

CREATE TABLE schedule (
    id                INTEGER NOT NULL,
    from_airport      VARCHAR2(40),
    to_airport        VARCHAR2(40),
    departure         DATE,
    arrival           DATE,
    economy_seats     INTEGER,
    business_seats    INTEGER,
    flight_status     VARCHAR2(10),
    b_seat_price      NUMBER(10, 2),
    e_seat_price      NUMBER(10, 2),
    flight_flight_no  INTEGER NOT NULL
);

ALTER TABLE schedule ADD CONSTRAINT schedule_pk PRIMARY KEY ( id );

CREATE TABLE transaction (
    id              VARCHAR2(30) NOT NULL,
    system_balance  NUMBER(10, 2)
);

ALTER TABLE transaction ADD CONSTRAINT transaction_pk PRIMARY KEY ( id );

CREATE TABLE user_details (
    id             INTEGER NOT NULL,
    user_name      VARCHAR2(40),
    first_name     VARCHAR2(40),
    last_name      VARCHAR2(40),
    email_id       VARCHAR2(40),
    password       VARCHAR2(60),
    date_of_birth  DATE,
    mobile_no      INTEGER,
    balance        NUMBER(15, 2)
);

ALTER TABLE user_details ADD CONSTRAINT user_details_pk PRIMARY KEY ( id );

ALTER TABLE bank_account
    ADD CONSTRAINT bank_account_user_details_fk FOREIGN KEY ( user_details_id )
        REFERENCES user_details ( id );

ALTER TABLE booking
    ADD CONSTRAINT booking_flight_fk FOREIGN KEY ( flight_flight_no )
        REFERENCES flight ( flight_no );

ALTER TABLE booking
    ADD CONSTRAINT booking_user_details_fk FOREIGN KEY ( user_details_id )
        REFERENCES user_details ( id );

ALTER TABLE log
    ADD CONSTRAINT log_booking_fk FOREIGN KEY ( booking_pnr )
        REFERENCES booking ( pnr );

ALTER TABLE passenger
    ADD CONSTRAINT passenger_booking_fk FOREIGN KEY ( booking_pnr )
        REFERENCES booking ( pnr );

ALTER TABLE schedule
    ADD CONSTRAINT schedule_flight_fk FOREIGN KEY ( flight_flight_no )
        REFERENCES flight ( flight_no );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0





--ADMIN TABLE
INSERT INTO admin VALUES(1,'sasidhar','password1');
INSERT INTO admin VALUES(2,'pranay','password2');
INSERT INTO admin VALUES(3,'shreya','password3');
INSERT INTO admin VALUES(4,'harishma','password4');


--USER_DETAILS TABLE
INSERT INTO user_details VALUES(1,'user1','first1','last1','email1','pass1','06-01-1982',9876543211,1000);
INSERT INTO user_details VALUES(2,'user2','first2','last2','email2','pass2','25-04-1993',9876543212,1100);
INSERT INTO user_details VALUES(3,'user3','first3','last3','email3','pass3','12-02-1995',9876543213,1200);
INSERT INTO user_details VALUES(4,'user4','first4','last4','email4','pass4','17-11-2001',9876543214,1300);
INSERT INTO user_details VALUES(5,'user5','first5','last5','email5','pass5','23-01-2012',9876543215,1400);
INSERT INTO user_details VALUES(6,'user6','first6','last6','email6','pass6','30-05-1999',9876543216,1500);
INSERT INTO user_details VALUES(7,'user7','first7','last7','email7','pass7','06-08-1994',9876543217,1600);
INSERT INTO user_details VALUES(8,'user8','first8','last8','email8','pass8','09-09-1990',9876543218,1700);



--BANK ACCOUNT TABLE
INSERT INTO bank_account VALUES(1,'citibank',20000,1);
INSERT INTO bank_account VALUES(2,'canara bank',35000,1);
INSERT INTO bank_account VALUES(3,'citibank',50000,2);
INSERT INTO bank_account VALUES(4,'indian overseas bank',75000,3);


--TRANSACTION TABLE             only one record is enough
INSERT INTO transaction VALUES(1,0);


--FLIGHT TABLE
INSERT INTO flight VALUES(1,'indigo');
INSERT INTO flight VALUES(2,'spice jet');
INSERT INTO flight VALUES(3,'air india');
INSERT INTO flight VALUES(4,'jet airways');
INSERT INTO flight VALUES(5,'kingfisher');


--SCHEDULE TABLE
INSERT INTO schedule VALUES
(1,'chennai','mumbai',
TO_DATE('06-01-2020 04:30','DD-MM-YYYY HH24:MI'),
TO_DATE('06-01-2020 10:30','DD-MM-YYYY HH24:MI'),
100,20,'ACTIVE',4500,3200,1);
INSERT INTO schedule VALUES
(2,'pune','mumbai',
TO_DATE('07-01-2020 18:30','DD-MM-YYYY HH24:MI'),
TO_DATE('08-01-2020 03:30','DD-MM-YYYY HH24:MI'),
100,20,'ACTIVE',4850,3550,2);




--use this query to check how the data is inserted into the table for date datatypes
--select to_char(TO_DATE('06-01-2020 04:30','DD-MM-YYYY HH24:MI'),'DD-MM-YYYY HH24:MI') from dual;



--DROPPING ALL TABLES

DROP TABLE bank_account;
DROP TABLE schedule;
DROP TABLE passenger;
DROP TABLE log;
DROP TABLE booking;
DROP TABLE flight;
DROP TABLE admin;
DROP TABLE transaction;
DROP TABLE user_details;


